"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import ItemView_ from "./components/ItemView_";
import Model_ from "./components/Model_";
import Footer_ from "./components/Footer_";
import SideBar_ from "./components/SideBar_";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><RecoilRoot>
        {children}
        <ItemView_ />
        <Model_/>
        <SideBar_/>
      {/* <Footer_/> */}
      </RecoilRoot></body>
    </html>
  );
}